
export interface ProductionSpecs {
  camera: string;   // e.g. "Slow zoom in from full body..."
  lighting: string; // e.g. "Clinical blue background..."
  sound: string;    // e.g. "Subtle ambient hum..."
}

export interface Scene {
  id: string;
  number: number;
  narrative: string;
  visualPrompt: string; // This corresponds to "AI Visual Directives"
  productionSpecs: ProductionSpecs; // NEW: Director notes
  estimatedDuration: number;
  assetUrl?: string;
  assetType: 'image' | 'video';
  // Added 'keyframeUrl' to store the high-res image used as base for video
  keyframeUrl?: string; 
  // NEW: Store the generated audio for this scene
  audioUrl?: string;
  audioDuration?: number; // in seconds
  status: 'pending' | 'generating' | 'done' | 'error';
  // New: stores specific status message like "Polling (15s)..."
  progressMessage?: string;
  logs: string[];
}

export interface StyleProfile {
  visualStyle: string; // e.g. "Low-poly 3D animation"
  pacing: string;      // e.g. "Slow and deliberate"
  tone: string;        // e.g. "Empathetic and reassuring"
  colorPalette: string[];
  targetAudience: string;
  keyElements: string[];
  // NEW: Analysis of HOW the video teaches
  pedagogicalApproach: string; // e.g. "Uses metaphors to explain biology"
  narrativeStructure: string[];  // UPDATED: Array of beats e.g. ["Hook: Problem", "Body: Analogy", "Conclusion"]
  scriptStyle: string; // e.g. "Short, punchy sentences with rhetorical questions"
  // NEW: Full transcript and quantitative pacing metrics
  fullTranscript: string; 
  wordCount: number;
  wordsPerMinute: number;
  
  // NEW: Precise duration of the source video in seconds.
  // Used to calculate exact "Seconds Per Word" ratio for perfect timing matching.
  sourceDuration?: number;

  // NEW: Persist the aspect ratio in the profile so imports work correctly
  targetAspectRatio?: "16:9" | "9:16";

  // METADATA FOR EXPORT/IMPORT
  _meta?: {
    sourceTitle: string;
    sourceThumbnail: string; // Base64 data URI
  };
}

export interface Fact {
  content: string;
  source: string;
  confidence: string;
}

export interface ResearchData {
  facts: Fact[];
  myths: string[];
  glossary: { term: string; definition: string }[];
  rawGroundingMetadata?: any; // To store the raw grounding chunks from Gemini
}

export interface NarrativeBeat {
  sectionTitle: string;
  description: string; // The strategic goal of this section
  estimatedDuration: number; // in seconds
  factReferences: string[]; // List of facts/concepts used here
}

export type NarrativeMap = NarrativeBeat[];

export interface VerificationReport {
  safetyCheck: boolean;
  medicalFlag: boolean;
  styleConsistencyScore: number;
  factCheckPassed: boolean;
}

export interface LogEntry {
  id: string;
  timestamp: string;
  message: string;
  type: 'info' | 'success' | 'error' | 'warning';
}

export interface ScriptVersion {
  id: string;
  label: string;
  content: string;
  timestamp: string;
}

export interface AppState {
  // Navigation/Layout state is implied by data presence now
  referenceVideoUrl: string | null;
  // NEW: Metadata for display in InputPanel
  referenceTitle?: string;
  referenceThumbnailUrl?: string;

  targetTopic: string;
  
  // NEW: Dynamic Aspect Ratio based on input video
  targetAspectRatio: "16:9" | "9:16";

  // Data
  styleProfile: StyleProfile | null;
  researchData: ResearchData | null;
  narrativeMap: NarrativeMap | null; // NEW
  draftScript: string | null; // The intermediate script generated by AI
  scriptVersions: ScriptVersion[]; // NEW: History of script drafts
  referenceSheetUrl: string | null; // The "Visual Anchor" image
  scenes: Scene[];
  
  // UI State
  logs: LogEntry[];
  // Removed old 'steps' (ProductionStep) and 'activeTab' as they are superseded by pipeline state
  isProcessing: boolean;
  verificationReport: VerificationReport | null;
  
  // Global
  error: string | null;
  apiKeySet: boolean;
  
  // NEW: Final Video URL
  finalVideoUrl?: string;
}

export enum ModelType {
  // --- HACKATHON CORE MODELS (GEMINI 3 SERIES) ---

  // 1. Complex Reasoning & Multimodal Analysis
  // Used for: Video Analysis (Style DNA), Script Writing, Narrative Mapping
  // Why: Best-in-class reasoning and multimodal input handling.
  ANALYSIS = 'gemini-3-pro-preview',
  SCRIPTING = 'gemini-3-pro-preview', 
  
  // 2. High-Fidelity Creative Generation
  // Used for: Visual Anchors, Storyboard Keyframes
  // Why: Specific support for "imageSize" and high-quality artistic control.
  IMAGE_GEN = 'gemini-3-pro-image-preview', 
  
  // 3. High-Speed & Efficiency
  // Used for: Research (Search Grounding), Safety Classification
  // Why: Low latency for interactive tasks; verified Search Grounding support.
  RESEARCH = 'gemini-3-flash-preview',
  SAFETY = 'gemini-3-flash-preview',

  // 4. Audio Generation
  // Used for: Narration (TTS)
  TTS = 'gemini-2.5-flash-preview-tts',

  // Fallback
  TEXT_FALLBACK = 'gemini-3-flash-preview',
}

// --- NEW PIPELINE & TEMPLATE DEFINITIONS ---

// Define concrete stages of the pipeline
export type PipelineStage = 
  | 'RESEARCH'      // 调研阶段
  | 'STRATEGY'      // 策略与 StyleDNA 定义阶段
  | 'SCRIPTING'     // 脚本撰写阶段
  | 'STORYBOARD'    // 分镜设计阶段
  | 'PRODUCTION';   // 最终生产阶段

// Define status for a single stage
export type ProcessStatus = 'pending' | 'processing' | 'completed' | 'error';

// Interface for pipeline step status tracking
export interface PipelineStepStatus {
  stage: PipelineStage;
  label: string;
  status: ProcessStatus;
  description?: string;
}

// Template Interface Definition (Reference VTSG Design)
export interface VideoTemplate {
  id: string;
  name: string;
  description: string;
  category: 'educational' | 'marketing' | 'vlog';
  defaultStyleDNA: {
    tone: string;
    visualStyle: string;
    pacing: 'slow' | 'medium' | 'fast';
  };
  narrativeStructure: string[]; // Preset narrative logic steps
}
